In [1]:
import numpy as np
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [ ]:
b = np.zeros(2)
b

In [ ]:
c = np.ones(3)
c

In [ ]:
d = np.empty(3)
d

In [ ]:
e = np.arange(6)
e

In [ ]:
f = np.arange(2, 20)
f

In [ ]:
g = np.arange(2, 20, 2)
g

In [21]:
h = np.linspace(0, 10, num=5)
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
i = np.ones(5, dtype=np.int8)
i

In [ ]:
j = np.ones(3, dtype=np.float64)
j

In [ ]:
k = np.zeros([3, 4])
k

In [ ]:
l = np.ones([5, 6])
l

In [5]:
import numpy as np
m = np.empty([4, 4])
m

array([[6.23042070e-307, 3.56043053e-307, 1.60219306e-306,
        7.56571288e-307],
       [1.89146896e-307, 1.37961302e-306, 1.05699242e-307,
        8.01097889e-307],
       [1.78020169e-306, 7.56601165e-307, 1.02359984e-306,
        1.33510679e-306],
       [2.22522597e-306, 6.23053614e-307, 1.60221072e-306,
        1.42410974e-306]])

In [7]:
cx = np.arange(24).reshape(2, 3, 4)
cx

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [8]:
food = np.array(["pakora", "samosa", "raita"])
food

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [9]:
price = np.array([40, 35, 15])
price

array([40, 35, 15])

In [10]:
type(price)

numpy.ndarray

In [11]:
len(food)

3

In [14]:
price[0]

40

In [15]:
price[0:]

array([40, 35, 15])

In [16]:
price.mean()

30.0

In [20]:
np.arange(5, 51, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

# Array function

In [25]:
aa = np.array([10,12,15,2,4,6,100,320,0.5,10.3])
aa

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [27]:
aa.sort()
aa

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [28]:
bb = np.array([10.2,3.4,53.6,91.6,45.5])
bb

array([10.2,  3.4, 53.6, 91.6, 45.5])

In [31]:
cc = np.concatenate([aa,bb])
cc

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6,  91.6,  45.5])

In [33]:
cc.sort()
cc

array([  0.5,   2. ,   3.4,   4. ,   6. ,  10. ,  10.2,  10.3,  12. ,
        15. ,  45.5,  53.6,  91.6, 100. , 320. ])

# 2-D Array

In [41]:
n = np.array([[1,2], [5,4]])
n

array([[1, 2],
       [5, 4]])

In [42]:
o = np.array([[6,7], [7,8]])
o

array([[6, 7],
       [7, 8]])

In [45]:
np.concatenate((n,o), axis=0)

array([[1, 2],
       [5, 4],
       [6, 7],
       [7, 8]])

In [46]:
np.concatenate((n,o), axis=1)

array([[1, 2, 6, 7],
       [5, 4, 7, 8]])

In [47]:
p = np.array([[[0,1,2,3],[4,5,6,7]], [[0,1,2,3],[4,5,6,7]], [[0,1,2,3],[4,5,6,7]]])
p

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [49]:
p.ndim

3

In [51]:
q = np.array([[4,5,6],[8,5,2],[7,5,3]])
q

array([[4, 5, 6],
       [8, 5, 2],
       [7, 5, 3]])

In [52]:
q.ndim

2

In [53]:
p.size

24

In [55]:
type(p)

numpy.ndarray

In [56]:
p.shape

(3, 2, 4)

In [67]:
r = np.arange(6)
r

array([0, 1, 2, 3, 4, 5])

In [69]:
s = r.reshape(2, 3)
s

array([[0, 1, 2],
       [3, 4, 5]])

In [2]:
t = np.array([1,2,3,4,5,6,7,8,9])
t

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
t[2:6]

array([3, 4, 5, 6])

In [13]:
t*5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [14]:
t+7

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16])

In [15]:
t.sum()

45

In [16]:
t.mean()

5.0

In [4]:
u = t.reshape(3, 3)
u

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
t.shape

(9,)

In [5]:
u.shape

(3, 3)

In [7]:
v = t[np.newaxis, :]
v

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [8]:
v.shape

(1, 9)

In [10]:
w = t[ : , np.newaxis]
w

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])